import './globals.css'
import type { Metadata } from 'next'
import { Italiana } from 'next/font/google'

const inter = Italiana({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Aluroni',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
